[package]
edition = "2018"
name = "parser"
version = "0.1.0"
authors = ["Jonathan Kingston <jonathan@jooped.co.uk>"]

[dependencies]
sourcefile = "0.1"
failure = "0.1.2"
weedle = "0.6"
heck = "0.3"
wasm-bindgen = { git = 'https://github.com/rustwasm/wasm-bindgen.git' }
