[package]
name = "dom"
version = "0.1.0"
authors = ["Alex Crichton <alex@alexcrichton.com>"]

[lib]
crate-type = ["cdylib"]

[dependencies]
wurst = { path = "../.." }
wasm-bindgen = "0.2.23"
web-sys = "0.3.0"
