[package]
name = "codegen"
version = "0.1.0"
authors = ["Jonathan Kingston <jonathan@jooped.co.uk>"]

[dependencies]
proc-macro2 = "0.4.13"
quote = '0.6'
parser = { path = "../parser", version = "0.1" }
